#!/bin/bash
#Program:
#   Ping a series of sites
#History:
#2012/12/05 SetoKaiba   First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

read -p "Enter IP like 127.0.1 :" network
for sitenu in $(seq 0 255)
do
    ping -c 1 -w 1 ${network}.${sitenu} &> /dev/null && result=0 || result=1

    if [ "$result" == 0 ]; then
        echo "Server ${network}.${sitenu} is UP."
    else
        echo "Server ${network}.${sitenu} is DOWN."
    fi
done
