#!/bin/bash
#Program:
#   This program shows "Hello World!" in your screen.
#History:
#2012/12/05 SetoKaiba   First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

read -p "Please enter a directory name :" dir
if [ "$dir" == "" -o ! -d "$dir" ]; then
    echo "$dir not exist."
    exit 1
fi

filelist=$(ls $dir)
for filename in $filelist
do
    perm=""
    test -r "$dir/$filename" && perm="$perm r"
    test -w "$dir/$filename" && perm="$perm w"
    test -x "$dir/$filename" && perm="$perm e"
    echo "The file $dir/$filename's permission is$perm"
done
