#!/bin/bash
#Program:
#   This program shows "Hello World!" in your screen.
#History:
#2012/12/05 SetoKaiba   First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

accounts=`cat /etc/passwd | cut -d ':' -f1`
for account in $accounts
do
    declare -i i=$i+1
    echo "The $i account is \"$account\""
done
